from autocode.primitives.cls import Class
from autocode.primitives.definable import Definable
from autocode.primitives.document import Document
from autocode.primitives.enum import Enum
from autocode.primitives.field import Field
from autocode.primitives.function import Function
from autocode.primitives.nameable import Nameable
from autocode.primitives.property import Property
from autocode.primitives.type import Type
from autocode.primitives.var import Var
